title: VenHuizen Family Ministries
email: thevenhuizens@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Our mission is to cultivate individual transformation 
  by ensuring access to the Bible, providing insightful training, 
  and fostering a deeper engagement with God through His Word.
baseurl: "/venhuizen-family-ministries" # the subpath of your site, e.g. /blog
url: "keithvenh.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
plugins:
  - jekyll-feed